version: '3.7'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile_front
    volumes:
      - ./front:/usr/src/front
      - /usr/src/front/node_modules
    working_dir: /usr/src/front
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true