name: jest
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: yarn install
      run: yarn install
      working-directory: ./front
    - name: Run jest
      run: yarn jest
      working-directory: ./front